#!/bin/sh

IFACE="$1"
IFNAME="pptp-mujjus"
TABLE_ID="100"
PREF="100"
FWMARK="100"

if [ "$IFACE" != "$IFNAME" ]; then
	exit 0
fi

logger "$IFNAME policy routing stoping..."

ip rule del fwmark $FWMARK lookup $TABLE_ID pref $PREF
ipset flush rtbl

logger "$IFNAME policy routing is down."
